Convert to a bashrc.d type system.
Debian systemd have a ~/.bashrc.d that lets the  system install scripts
for a user.  It's nice and flexible, so this models after that.

Add a bashrc.d/actions/, bashrc.d/env/, bashrc.d/flavor/, and
bashrc.d/local/ to the scripts repo.

During setup, bashrc.d/local is copied to $HOME/.bashrc.d/.

Login happens like this:

- First, bashrc.d/env/* is sourced, to set up the base environment.
  - This includes setting the flavor of linux
- Next ${HOME}/.bashrc.d/ is sourced to override the env locally.
- Next bashrc.d/actions/* is sourced, to set common aliases/commands
- Finally, bashrc.d/flavor/$FLAVOR/* is sourced to set up for the
  flavor.

diff --git a/flavor/gentoo/dsync b/flavor/gentoo/dsync
--- a/flavor/gentoo/dsync
+++ b/flavor/gentoo/dsync
@@ -9,7 +9,7 @@ LONGUSAGE="\t-h\tPrint this help message
 \t-v\tBe verbose"
 
 # Standard functions
-source ${HOME}/.scripts/functions.sh
+source ${SCRIPTS}/functions.sh
 
 ECVSUPARGS=""
 # Parse arguments
@@ -29,12 +29,12 @@ if [ "${OPTIND}" != "0" ]; then
        shift $((OPTIND-1))
 fi
 
-${HOME}/.scripts/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
+${SCRIPTS}/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
 sudo cp /var/cache/eix/portage.eix /var/cache/eix/previous.eix || die "Error while copying cache-file to a save location."
 sudo eix-update                         || die "Problems with eix-update."
 sudo eix-diff /var/cache/eix/previous.eix || die "Error while diffing."
 if [ -z "${NOSYSCSCOPE}" ]; then
 	cd /usr/src/debug
-	sudo ${HOME}/.scripts/maketags -k
+	sudo ${SCRIPTS}/maketags -k
 fi
 exit 0
