Convert scriptdir references
Move all reverences to ${HOME}/bin/scripts to ${SCRIPTS}

diff --git a/dsync b/dsync
--- a/dsync
+++ b/dsync
@@ -7,7 +7,7 @@ LONGUSAGE="\t-h\tPrint this help message
 \t-n\tSkip updating overlays"
 
 # Standard functions
-source ${HOME}/bin/scripts/functions.sh
+source ${SCRIPTS}/functions.sh
 
 ECVSUPARGS=""
 # Parse arguments
@@ -25,7 +25,7 @@ if [ "${OPTIND}" != "0" ]; then
        shift $((OPTIND-1))
 fi
 
-${HOME}/bin/scripts/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
+${SCRIPTS}/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
 tmpfile=$(mktemp)
 sudo cp /var/cache/eix ${tmpfile} || die "Error while copying cache-file to a save location."
 sudo update-eix                         || die "Problems with update-eix."
