changelog support for ebump
git-svn-id: https://nemesis.fprintf.net/svn/scripts@316 6a022d3a-3905-0410-ac87-c01684601b3d

diff --git a/dsync b/dsync
--- a/dsync
+++ b/dsync
@@ -1,47 +1,31 @@
 #!/bin/bash
-# Author: Emil Beinroth <emilbeinroth@gmx.net>
 
-###########################################################################
-#   eix is a small utility for searching ebuilds in the                   #
-#   Gentoo Linux portage system. It uses indexing to allow quick searches #
-#   in package descriptions with regular expressions.                     #
-#                                                                         #
-#   https://sourceforge.net/projects/eix                                  #
-#                                                                         #
-#   Copyright (c)                                                         #
-#     Wolfgang Frisch <xororand@users.sourceforge.net>                    #
-#     Emil Beinroth <emilbeinroth@gmx.net>                                #
-#                                                                         #
-#   This program is free software; you can redistribute it and/or modify  #
-#   it under the terms of the GNU General Public License as published by  #
-#   the Free Software Foundation; either version 2 of the License, or     #
-#   (at your option) any later version.                                   #
-#                                                                         #
-#   This program is distributed in the hope that it will be useful,       #
-#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
-#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
-#   GNU General Public License for more details.                          #
-#                                                                         #
-#   You should have received a copy of the GNU General Public License     #
-#   along with this program; if not, write to the                         #
-#   Free Software Foundation, Inc.,                                       #
-#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
-###########################################################################
+# Set usage output
+USAGE="[-hfn]"
+LONGUSAGE="\t-h\tPrint this help message
+\t-f\tFast update (no metadata regen)
+\t-n\tSkip updating overlays"
 
+# Standard functions
 source ${HOME}/bin/scripts/functions.sh
 
-GNOME_OVERLAY="/home/portage/overlays/gnome"
+ECVSUPARGS=""
+# Parse arguments
+while getopts ":hfn:" option; do
+       case ${option} in
+               f ) ECVSUPARGS="${ECVSUPARGS} -f";;
+               n ) ECVSUPARGS="${ECVSUPARGS} -n";;
+               h ) usage;;
+               \? ) usage "Invalid argument ${OPTARG}";;
+               * ) usage "Invalid argument ${option}";;
+       esac
+done
 
-function die() {
-	eerror "$@"
-	exit 1
-}
+if [ "${OPTIND}" != "0" ]; then
+       shift $((OPTIND-1))
+fi
 
-[ "${#}" -ne 0 ] && {
-	usage ""
-}
-
-${HOME}/bin/scripts/ecvsup || die "Error during ecvsup"
+${HOME}/bin/scripts/ecvsup ${ECVSUPARGS} || die "Error during ecvsup"
 tmpfile=$(mktemp)
 sudo cp /var/cache/eix ${tmpfile} || die "Error while copying cache-file to a save location."
 sudo update-eix                         || die "Problems with update-eix."
diff --git a/ebump b/ebump
--- a/ebump
+++ b/ebump
@@ -20,6 +20,7 @@ USAGE="[-hcbk][-p <portdir>] [-t <tmpdir>] [-d <distdir>]  <basename> <old-versi
 LONGUSAGE="\t-h\tPrint this help message
 \t-b\tBuild package.
 \t-c\tCommit package when done.
+\t-C\tView ChangeLog when done.
 \t-k\tKeep old versions.
 \t-p <portdir>\tPORTDIR to act on (default ${PORTDIR})
 \t-t <tmpdir>\tTMP directory to extract packages to (default ${TMPDIR})
@@ -32,9 +33,10 @@ LONGUSAGE="\t-h\tPrint this help message
 source ${HOME}/bin/scripts/functions.sh
 
 # Parse arguments
-while getopts ":hcbkp:d:t:" option; do
+while getopts ":hcCbkp:d:t:" option; do
 	case ${option} in
 		c ) COMMIT="yes";;
+		C ) CHANGELOG="yes";;
 		b ) BUILD="yes";;
 		k ) RMOLD="no";;
 		p ) PORTDIR=${OPTARG};;
@@ -84,20 +86,29 @@ fi
 echo "Adding ${NEWEBUILD} and ${NEWDIGEST}"
 
 # Make ebuild change
-cp ${OLDEBUILD} ${NEWEBUILD} || die "cp failed"
-if [ "${RMOLD}" == "yes" ]; then
-	vcs_rm ${OLDEBUILD} ${OLDDIGEST}
+if [ "${OLDEBUILD}" != "${NEWEBUILD}" ]; then
+	cp ${OLDEBUILD} ${NEWEBUILD} || die "cp failed"
+	if [ "${RMOLD}" == "yes" ]; then
+		vcs_rm ${OLDEBUILD} ${OLDDIGEST}
+	fi
 fi
 ebuild ${NEWEBUILD} digest || die "digest failed"
 [ -f ${NEWDIGEST} ] || die "${NEWDIGEST} doesn't exist"
 # Add to VCS
-vcs_add ${NEWEBUILD} ${NEWDIGEST}
-echangelog "Bump to ${NEWVER}" || die "echangelog failed"
+if [ "${OLDEBUILD}" != "${NEWEBUILD}" ]; then
+	vcs_add ${NEWEBUILD} ${NEWDIGEST}
+fi
 
 # Open up the new ebuild and the configure.(in|ac) to check for new deps
 cd ${TMPDIR} || die "No ${TMPDIR}"
 duntarball ${DISTDIR}/${BASENAME}-${NEWVER}.tar.bz2 || duntarball ${DISTDIR}/${BASENAME}-${NEWVER}.tar.gz
 gvim -f -geometry 177x47 -O ${EBUILDDIR}/${NEWEBUILD} ${BASENAME}-${NEWVER}/configure.*
+if [ -n "${CHANGELOG}" ]; then
+	# Want the changelog
+	TEMPFILE=$(tempfile)
+	cp ${BASENAME}-${NEWVER}/ChangeLog ${TEMPFILE}
+fi
+
 rm -rf ${BASENAME}-${NEWVER}
 cd -
 
@@ -109,9 +120,22 @@ if [ -n "${BUILD}" ]; then
 	sudo emerge ${BASENAME} || die "emerge failed"
 fi
 
+VCS_COMMITFILE=$(tempfile)
+echo "Bump to ${NEWVER}" >> ${VCS_COMMITFILE}
+
+if [ -n "${CHANGELOG}" ]; then
+	gvim -f -geometry 177x47 -O ${TEMPFILE} ${VCS_COMMITFILE}
+	rm ${TEMPFILE}
+fi
+
+ECHANGELOG_EDITOR= echangelog-tng < ${VCS_COMMITFILE} || die "echangelog failed"
+# Re-digest
+ebuild ${NEWEBUILD} digest || die "digest failed"
+
 if [ -n "${COMMIT}" ]; then
 	# We were told to commit it
-	vcs_commit "Bump to ${NEWVER}"
+	# Uses VCS_COMMITFILE
+	vcs_commit
 fi
 
 # Tell user we're done
diff --git a/ecvsup b/ecvsup
--- a/ecvsup
+++ b/ecvsup
@@ -3,15 +3,46 @@
 # Sync portage tree via CVS
 #
 
+USAGE="[-hfn]"
+LONGUSAGE="\t-h\tPrint this help message
+\t-f\tFast update (no metadata regen)
+\t-n\tSkip updating overlays"
+
+# Standard functions
 source ${HOME}/bin/scripts/functions.sh
+
+# PORTDIR_OVERLAY
+source /etc/make.conf
+
+# Parse arguments
+while getopts ":hfn" option; do
+       case ${option} in
+               f ) FAST="yes";;
+               n ) NOOVERLAYS="yes";;
+               h ) usage;;
+               \? ) usage "Invalid argument ${OPTARG}";;
+               * ) usage "Invalid argument ${option}";;
+       esac
+done
 
 cd /usr/portage || die "no /usr/portage"
 # Removed -C, because it touches mtime of every file, causing a full regen
 cvs -q up -PdA || die "cvs up failed"
 find /usr/portage -name '.#*' -exec rm {} \; || die "find .#* failed"
+if [ -z "${NOOVERLAYS}" ]; then
+	for i in ${PORTDIR_OVERLAY}; do
+		cd ${i}
+		vcs_detect
+		vcs_update
+	done
+fi
 cd /home/portage/overlays/dangtopia/ || die "no dangtopia"
 svn up || die "svn up of dangtopia failed"
+cd /home/portage/overlays/gentopia/ || die "no gentopia"
+svn up || die "svn up of gentopia failed"
 cd /home/portage/overlays/gnome/ || die "no gnome"
 svn up || die "svn up of gnome failed"
-sudo emerge --regen || die "emerge regen failed"
-sudo emerge --metadata || die "emerge metadata failed"
+if [ -z "${FAST}" ]; then
+	sudo emerge --regen || die "emerge regen failed"
+	sudo emerge --metadata || die "emerge metadata failed"
+fi
