Emerge the specific version being bumped, and use oneshot to not affect the world file
git-svn-id: https://nemesis.fprintf.net/svn/scripts@358 6a022d3a-3905-0410-ac87-c01684601b3d

diff --git a/ebump b/ebump
--- a/ebump
+++ b/ebump
@@ -142,7 +142,7 @@ ebuild ${NEWEBUILD} digest || die "digest failed"
 
 if [ -n "${BUILD}" ]; then
 	# We were told to build it
-	emerge ${PORT_CATEGORY}/${PN} || die "emerge failed"
+	emerge --oneshot "=${PORT_CATEGORY}/${PN}-${PVR}" || die "emerge failed"
 fi
 
 VCS_COMMITFILE=$(tempfile)
