Change digest to manifest, and force

diff --git a/ebump b/ebump
--- a/ebump
+++ b/ebump
@@ -170,8 +170,8 @@ if [ "${OLDEBUILD}" != "${NEWEBUILD}" ]; then
 	fi
 fi
 
-# digest new ebuild
-ebuild ${NEWEBUILD} digest || die "digest failed"
+# manifest new ebuild
+ebuild ${NEWEBUILD} --force manifest || die "manifest failed"
 # Make sure we have the tarballs
 sudo emerge -f =${PF}
 
@@ -197,8 +197,8 @@ fi
 rm -rf ${DIRNAME}
 cd -
 
-# Now re-digest in case the ebuild changed
-ebuild ${NEWEBUILD} digest || die "digest failed"
+# Now re-manifest in case the ebuild changed
+ebuild ${NEWEBUILD} --force manifest || die "manifest failed"
 
 
 if [ -n "${BUILD}" ]; then
@@ -220,8 +220,8 @@ fi
 
 vcs_echangelog
 
-# Re-digest
-ebuild ${NEWEBUILD} digest || die "digest failed"
+# Re-manifest
+ebuild ${NEWEBUILD} --force manifest || die "manifest failed"
 
 if [ -n "${COMMIT}" ]; then
 	# We were told to commit it
