Use echangelog for portage; echangelog-tng doesn't seem to detect changed files
git-svn-id: https://nemesis.fprintf.net/svn/scripts@363 6a022d3a-3905-0410-ac87-c01684601b3d

diff --git a/ebump b/ebump
--- a/ebump
+++ b/ebump
@@ -153,7 +153,11 @@ if [ -n "${CHANGELOG}" ]; then
 	rm ${CLTEMPFILE} ${NTEMPFILE}
 fi
 
-ECHANGELOG_EDITOR= echangelog-tng < ${VCS_COMMITFILE} || die "echangelog failed"
+if [ "${VCS}" == "cvs" ]; then
+	ECHANGELOG_EDITOR= echangelog < ${VCS_COMMITFILE} || die "echangelog failed"
+else
+	ECHANGELOG_EDITOR= echangelog-tng < ${VCS_COMMITFILE} || die "echangelog failed"
+fi
 # Re-digest
 ebuild ${NEWEBUILD} digest || die "digest failed"
 
