Fix find to ignore lost+found

diff --git a/ecvsup b/ecvsup
--- a/ecvsup
+++ b/ecvsup
@@ -42,7 +42,7 @@ cd ${PORTDIR} || die "no ${PORTDIR}"
 # Removed -C, because it touches mtime of every file, causing a full regen
 trace "Updating ${PORTDIR}"
 cvs -q up -PdA || die "cvs up failed"
-find ${PORTDIR} -name '.#*' -exec rm {} \; || die "find .#* failed"
+find . -name 'lost+found' -prune -o \( -name '.#*' -exec rm {} \; \) || die "find .#* failed"
 if [ -z "${NOOVERLAYS}" ]; then
 	for i in ${PORTDIR_OVERLAY}; do
 		trace "updating $i"
