scripts-setup - add braindead mode
Some environments don't seem to be able to pass associative arrays as
arguments.  'declare -A' doesn't work in functions.  For these
environments, add a --braindead mode that generates a temporary flat
script to set up symlinks.

Signed-off-by: Daniel Gryniewicz <dang@fprintf.net>

diff --git a/scripts-setup b/scripts-setup
--- a/scripts-setup
+++ b/scripts-setup
@@ -9,9 +9,10 @@ REPO="git://github.com/dang/scripts.git"
 SCRIPTDIR="${HOME}/.scripts"
 
 # Set usage output
-USAGE="[-h |--help] [-f | --fixup] [<directory>]"
+USAGE="[-h |--help] [-f | --fixup] [-b <filename> | --braindead <filename> ] [<directory>]"
 LONGUSAGE="\t-h, --help\n\t\tPrint this help message
 \t-f, --fixup\n\t\tFix up homedir for new links/copies
+\t-b <filename>, --braindead <filename>\n\t\tGenerate a setup script for braindead systems
 \t<directory>\n\t\tScripts directory. Defaults to ${SCRIPTDIR}"
 
 # Standard functions
@@ -67,7 +68,7 @@ usage() {
 ME=$(basename $0)
 
 # Parse arguments
-ARGS=`getopt -o hf --long help,fixup -n "${ME}" -- "$@"`
+ARGS=`getopt -o hb:f --long help,braindead:fixup -n "${ME}" -- "$@"`
 
 if [ $? != 0 ] ; then
 	usage 
@@ -78,6 +79,7 @@ while true ; do
 	case "$1" in
 		-h|--help) usage; shift ;;
 		-f|--fixup) FIXUP="yes"; shift ;;
+		-b|--braindead) BRAINDEAD="$2"; shift 2 ;;
 		--) shift ; break ;;
 		* ) usage "Invalid argument $1";;
 	esac
@@ -139,7 +141,6 @@ function cmd_exists {
 function checkexists {
 	local _str_arr="$(declare -p $1)"
 	eval "local -A array=${_str_arr#*=}"
-	(
 	for k in "${!array[@]}"; do
 		for f in ${array[$k]}; do
 			local base="$k/$f"
@@ -147,12 +148,50 @@ function checkexists {
 				# no extra ./
 				base="$f"
 			fi
-			[ -a "${HOME}/${base}" ] && die "${HOME}/${base} exists; not continuing"
+			[ -a "${HOME}/${base}" ] && die "${HOME}/${base} exists; not continuing" || return 1
 		done
 	done
-	exit 0
-	)
-	return $?
+}
+
+# braindead ASSOC_ARRAY $outfile [$copy]
+#
+# Generate a script $outfile that will install scripts on a braindead system
+# that doesn't handle associative arrays properly.  If $copy is given and true,
+# copy files.  Otherwise, symlink them
+#
+# Note: do *not* dereference the array in the call
+function braindead {
+	local _str_arr="$(declare -p $1)"
+	eval "local -A array=${_str_arr#*=}"
+	local outfile=$2
+	local copy=$3
+	if [ -z "${outfile}" ]; then
+		die "No outfile" || return 1
+	fi
+	for k in "${!array[@]}"; do
+		for f in ${array[$k]}; do
+			local base="$k/$f"
+			if [ "$k" == "." ]; then
+				# no extra ./
+				base="$f"
+			fi
+			local basedir=$(dirname $base{})
+			echo mkdir -p "${HOME}/${basedir}" >> "${outfile}"
+			if [ -z "${copy}" ]; then
+				if [ -n "${FIXUP}" ]; then
+					echo rm "${HOME}/${base}" >> "${outfile}"
+				fi
+				echo ln -s "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" \|\| die "failed to link ${base}" >> "${outfile}"
+			else
+				if [ -n "${FIXUP}" ]; then
+					# Skip existing files
+					echo if [ ! -e "${HOME}/${base}" ]\; then >> "${outfile}"
+					echo cp -a "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" \|\| die "failed to copy ${base}" >> "${outfile}"
+					echo fi >> "${outfile}"
+				fi
+			fi
+		done
+	done
 }
 
 
@@ -166,7 +205,6 @@ function install {
 	local _str_arr="$(declare -p $1)"
 	eval "local -A array=${_str_arr#*=}"
 	local copy=$2
-	(
 	for k in "${!array[@]}"; do
 		for f in ${array[$k]}; do
 			local base="$k/$f"
@@ -180,7 +218,7 @@ function install {
 				if [ -n "${FIXUP}" ]; then
 					rm "${HOME}/${base}"
 				fi
-				ln -s "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to link ${base}"
+				ln -s "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to link ${base}" || return 1
 			else
 				if [ -n "${FIXUP}" ]; then
 					# Skip existing files
@@ -188,15 +226,23 @@ function install {
 						continue
 					fi
 				fi
-				cp -a "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to copy ${base}"
+				cp -a "${HOME}/.scripts/cfg/${base}" "${HOME}/${base}" || die "failed to copy ${base}" || return 1
 			fi
 		done
 	done
-	)
-	return $?
 }
 
 cmd_exists sed
+
+if [ -n "${BRAINDEAD}" ]; then
+	rm "${BRAINDEAD}"
+	echo "#!/bin/bash" > "${BRAINDEAD}"
+	echo 'die() { echo "Failed: $@"; exit 1; }' >> "${BRAINDEAD}"
+	braindead LNSET "${BRAINDEAD}"
+	braindead CPSET "${BRAINDEAD}"
+	echo "Wrote ${BRAINDEAD}"
+	exit
+fi
 
 if [ -z "${FIXUP}" ]; then
 	# Check for conflicts
